name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x easycontrol/gradlew
    - name: Build with Gradle
      working-directory: easycontrol
      run: ./gradlew build
    - name: Package Files
      run: |
        # Create a zip archive with all files in the specified directory
        cd /home/runner/work/Easycontrol/Easycontrol/easycontrol/app/
        zip -r my-package.zip .

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-package
        path: my-package.zip
